security:
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/cron, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/key, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
